version: '3.5'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_RETENTION=1
    volumes:
      - etcd-data:/etcd
    networks:
      - milvus-net

  milvus:
    image: milvusdb/milvus:v2.4.3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - etcd
    networks:
      - milvus-net
    command: ["milvus", "run", "standalone"]

volumes:
  etcd-data:

networks:
  milvus-net:
